# This template build a Flaks app to be deployed to a Azure WebApp with zip deploy.
# This template fetch variables from azure-pipeline.yml

jobs:
  - job: BuildJob
    displayName: Building Flask API for Azure WebApp

    pool:
      vmImage: $(vmImageName)

    variables:
      BUILD_ID: $(Build.BuildId)
      BUILD_NO: $(Build.BuildNumber)
      BUILD_VERSION: $(Build.SourceVersion)
      BUILD_REPO_NAME: $(Build.Repository.Name)
      BUILD_BRANCH: $(Build.SourceBranch)
      BUILD_BRANCH_NAME: $(Build.SourceBranchName)
      BUILD_DATE: $(system.pipelineStartTime)


    steps:

    # Legacy proj do not have build config template  
    - bash: |
       if [ -f /tmp/foo.txt ]; then
           echo "##vso[task.setvariable variable=fileExist]true"
       fi

    # Inject build info
    - task: FileTransform@1
      condition: eq(variables.fileExist, 'true')
      inputs:
        folderPath: $(projectRoot)
        fileType: 'json'
        targetFiles:
          '**/config_build.json'
      displayName: 'Insert build info'

    # Create zip
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/build$(Build.BuildId).zip
        replaceExistingArchive: true
      displayName: 'Create artifact (zip)'

    # upload, publish or task PublishPipelineArtifacts
    - upload: $(Build.ArtifactStagingDirectory)/build$(Build.BuildId).zip
      displayName: 'Upload (publish) artifact (in pipeline).'
      artifact: drop
